# Example of file
exercise_type: default
has_feedback: True
quorum: 1.0
feedback_kind: JavaGrading
prohibited:
  "student_map_orelse":
    - new TeamLeader
  "student_filter":
    - new TeamLeader
  "student_if_present":
    - new TeamLeader
  "student_flatmap":
    - new TeamLeader
