has_feedback: True
feedback_kind: JavaGrading
prohibited:
  "student_add":
    - new LinkedList
    - queue.pop
    - queue.push
    - queue.poll
    - queue.element
    - queue.get
    - queue.addFirst
    - queue.addLast
    - queue.offer
    - queue.removeFirst
    - queue.removeLast
  "student_remove":
    - new LinkedList
    - queue.pop
    - queue.push
    - queue.poll
    - queue.element
    - queue.get
    - queue.addFirst
    - queue.addLast
    - queue.offer
    - queue.removeFirst
    - queue.removeLast
  "student_peek":
    - new LinkedList
    - queue.pop
    - queue.push
    - queue.poll
    - queue.element
    - queue.get
    - queue.addFirst
    - queue.addLast
    - queue.offer
    - queue.removeFirst
    - queue.removeLast
  "student_isEmpty":
    - new LinkedList
    - queue.pop
    - queue.push
    - queue.poll
    - queue.element
    - queue.get
    - queue.addFirst
    - queue.addLast
    - queue.offer
    - queue.removeFirst
    - queue.removeLast
